[project]
name = "metron_shared"
requires-python = ">=3.11"
version = "0.1"
license = "MIT"
dependencies = [
    "hydra-core>=1.3.0",
    "typeguard>=4.4.4"
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"